### ISSUE TITLE
Overgrowth Seed

### ISSUE THREAD

**Issue by tbachman-w** [AllTheMods/All-the-mods-7-Sky#284]
The overgrowth seed needed for to make magical soil is only available in overworld dungeon chest and does not have any crafting recipe.

**Comment by Mitchell5200** [comment]
You can also get it from the gaia Guardian fight, as boss loot

**Comment by tbachman-w** [comment]
Which tier of fight lvl 1 or 2?  I have done them both a dozen times and haven't gotten it as a drop.

**Comment by Mitchell5200** [comment]
do you have Knowledge of the ages on your sword?

**Comment by tbachman-w** [comment]
No i do not

**Comment by phit** [comment]
its a [25%](https://github.com/VazkiiMods/Botania/blob/e6d095ff5010074b45408d6cce8ee1e328af3383/Xplat/src/main/resources/data/botania/loot_tables/gaia_guardian_2.json#L66-L75) drop chance, I had to kill 20 or so to just get a couple

right now this is making the magical soil route very much useless, you just have to spam phytogenic insolators for the top tier seeds or use the lasers added in 1.1.0 instead since they outclass pretty much any seed production

**Comment by tbachman-w** [comment]
Thanks for the advice.
