### ISSUE TITLE
Imbalance with ProjectE

### ISSUE THREAD

**Issue by RareMojo** [AllTheMods/All-the-mods-7-Sky#293]
This may be more of a subjective thing, but I just didn't feel like it was intended.

You can sieve gravel for items for example. You cannot get gravel with EMC though. So you still need to play other parts of the game to obtain gravel to sieve to get some resources.

Soul Sand _is_ transmutable and is worth only 8 EMC. Getting a single quartz will get you 64 more soul sand. You can see how this can get really out of control.

Simply make soul sand not transmutable like gravel and I'd imagine there's a few other instances of this type of exploit maybe.
Sorry if this is a dupe issue, but I did check with search.

**Comment by oly2o6** [comment]
kind of intentional, but gravel not having emc is not so ill get that sorted (the vision of projectE is it only gets you materials and basic blocks, so players sieving that into materials to feed the emc system again is fine, as by the time they get projectE most of these could have been easily done another way and they had to struggle through with no automation just to automate it in the midgame with ProjectE)
