### ISSUE TITLE
Hostile Neural Network Questing

### ISSUE THREAD

**Issue by OverBrewedLeaf** [AllTheMods/All-the-mods-7-Sky#328]
Got one prediction, all prediction quests were completed

![image](https://user-images.githubusercontent.com/64700348/199917746-1b0888e7-14ff-4f29-a6aa-655a84ef11b7.png)

**Comment by VeryGoodDev** [comment]
+1, just saw this as well. I'm guessing it's because every prediction is the same item; HNN uses NBT to determine which mob the prediction is for but I'm guessing the quest isn't checking for that (this also confused the hell out of me while I was trying to automate putting the predictions into loot fabricators)

**Comment by oly2o6** [comment]
Will be a workaround in the next update
