### ISSUE TITLE
LaserIO power transfer broken?

### ISSUE THREAD

**Issue by DanDanBro** [AllTheMods/All-the-mods-7-Sky#336]
I updated my ATM7 sky in the ftb app to 1.14. Now my laserIO nodes do not transfer any power anymore. Fluids and items still work.

**Comment by jay-dogg** [comment]
Having the same issue with power though laserIO  tryed using energy pipes and flux network to pass the power but nothing is working. fluid and items confirmed working still.

**Comment by jay-dogg** [comment]
Apprently this has been fixed in https://www.curseforge.com/minecraft/mc-mods/laserio/files 1.4.5

Something to do with flux networks

Update single player and server side manauly for now untill the pack dev has fixed this

=================TESTING THIS NOW WILL UPDATE ONCE CONFIRMED WORKING=================

**Comment by jay-dogg** [comment]
![2022-11-09_19 21 07](https://user-images.githubusercontent.com/4331911/200921909-11c651fe-8652-4afa-8338-504f0d6bcf31.png)


Can Confirm laserio 1.4.5 fixes the issues.

Manual Fix:

download mod 
https://www.curseforge.com/minecraft/mc-mods/laserio/files
Place laserio1..5 jar in to mods folder and delete
laserio 1.4.4
then launch pack / server.
Hopefull this will be fixed in next update by the devs.

**Comment by oly2o6** [comment]
it will be! new update coming soon with the fix 😃
