### ISSUE TITLE
The server drops when you right-click to place any block

### ISSUE THREAD

**Issue by KuroPeach** [AllTheMods/All-the-mods-7-Sky#34]
The server drops when you right-click to place any block
![{)UDWXXIZOX1OFG77RD%RKT](https://user-images.githubusercontent.com/19620848/184467501-1e2bc0f2-20f5-49b4-8da2-3622c717cb55.png)

The empty-handed right-click will not be offline, but the server background will always report an error
![image](https://user-images.githubusercontent.com/19620848/184468313-cb56cb96-4fe9-4625-912e-482975e90041.png)

**Comment by enigmaquip** [comment]
If you want to try, you can manually make the edits I did, or replace the text with what's here <https://github.com/AllTheMods/All-the-mods-7-Sky/blob/6809802da3c78a5c8d92e684c223a7b4d4967d71/kubejs/server_scripts/mod_specific/ex_nihilo/ex_nihilo_pebbles.js>
otherwise it should go out in the next update

**Comment by KuroPeach** [comment]
OK

**Comment by KuroPeach** [comment]
After the replacement, no error was reported, but the server performance was very bad.
![NDW0CE5NKQAFBA~)0AKXRPU](https://user-images.githubusercontent.com/19620848/184468797-fbb40497-ee4e-4c68-ab14-b8b3392a1945.png)

**Comment by jeremiahwinsley** [comment]
Run a Spark profile: https://spark.lucko.me/docs/guides/Finding-lag-spikes and post the results?

**Comment by KuroPeach** [comment]
Caused by the player using the linker
